name: Panhabu
version: '${project.version}'
main: plugin.panhabu.Panhabu
api-version: '1.20'
author: 'Jairusu'
description: 'A custom-built Minecraft plugin designed exclusively for the PandesalSMP server.'

commands:
  panhabu:
    description: 'command'
    permission: op
  prison:
    description: 'command'
    permission: op
    aliases:
      - jail
  release:
    description: 'command'
    permission: op
    aliases:
      - unjail
  setauth:
    description: 'command'
    permission: op
  setprison:
    description: 'command'
    permission: op
    aliases:
      - setjail
  setspawn:
    description: 'command'
    permission: op
  spawn:
    description: 'command'